#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Por favor, execute como root."
  exit 1
fi

rm -f /etc/hosts

cat <<EOL > /etc/hosts
::ffff:d10e:4618 sshplus.xyz
::ffff:d10e:4618 https://sshplus.xyz
152.67.54.71 https://sshplus.xyz
152.67.54.71 sshplus.xyz
EOL

echo "SUCESSO."
